apiVersion: v1
kind: Service
metadata:
  name: dotnet-fsharp
  namespace: dotnet-fsharp
  labels:
    app: dotnet-fsharp
spec:
  type: ClusterIP
  selector:
    app: dotnet-fsharp
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
